/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cn.atomicer.zephyr.raft.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3869767132978319803L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"cn.atomicer.zephyr.raft.model\",\"fields\":[{\"name\":\"requestId\",\"type\":\"string\"},{\"name\":\"mid\",\"type\":\"string\"},{\"name\":\"term\",\"type\":[\"int\",\"null\"]},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"data\",\"type\":[\"bytes\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Message> ENCODER =
      new BinaryMessageEncoder<Message>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Message> DECODER =
      new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Message> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Message> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Message to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Message from a ByteBuffer. */
  public static Message fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence requestId;
  @Deprecated public java.lang.CharSequence mid;
  @Deprecated public java.lang.Integer term;
  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.nio.ByteBuffer data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message() {}

  /**
   * All-args constructor.
   * @param requestId The new value for requestId
   * @param mid The new value for mid
   * @param term The new value for term
   * @param type The new value for type
   * @param data The new value for data
   */
  public Message(java.lang.CharSequence requestId, java.lang.CharSequence mid, java.lang.Integer term, java.lang.CharSequence type, java.nio.ByteBuffer data) {
    this.requestId = requestId;
    this.mid = mid;
    this.term = term;
    this.type = type;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return mid;
    case 2: return term;
    case 3: return type;
    case 4: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = (java.lang.CharSequence)value$; break;
    case 1: mid = (java.lang.CharSequence)value$; break;
    case 2: term = (java.lang.Integer)value$; break;
    case 3: type = (java.lang.CharSequence)value$; break;
    case 4: data = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.CharSequence getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'mid' field.
   * @return The value of the 'mid' field.
   */
  public java.lang.CharSequence getMid() {
    return mid;
  }

  /**
   * Sets the value of the 'mid' field.
   * @param value the value to set.
   */
  public void setMid(java.lang.CharSequence value) {
    this.mid = value;
  }

  /**
   * Gets the value of the 'term' field.
   * @return The value of the 'term' field.
   */
  public java.lang.Integer getTerm() {
    return term;
  }

  /**
   * Sets the value of the 'term' field.
   * @param value the value to set.
   */
  public void setTerm(java.lang.Integer value) {
    this.term = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Creates a new Message RecordBuilder.
   * @return A new Message RecordBuilder
   */
  public static cn.atomicer.zephyr.raft.model.Message.Builder newBuilder() {
    return new cn.atomicer.zephyr.raft.model.Message.Builder();
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message RecordBuilder
   */
  public static cn.atomicer.zephyr.raft.model.Message.Builder newBuilder(cn.atomicer.zephyr.raft.model.Message.Builder other) {
    return new cn.atomicer.zephyr.raft.model.Message.Builder(other);
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Message instance.
   * @param other The existing instance to copy.
   * @return A new Message RecordBuilder
   */
  public static cn.atomicer.zephyr.raft.model.Message.Builder newBuilder(cn.atomicer.zephyr.raft.model.Message other) {
    return new cn.atomicer.zephyr.raft.model.Message.Builder(other);
  }

  /**
   * RecordBuilder for Message instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.lang.CharSequence requestId;
    private java.lang.CharSequence mid;
    private java.lang.Integer term;
    private java.lang.CharSequence type;
    private java.nio.ByteBuffer data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cn.atomicer.zephyr.raft.model.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mid)) {
        this.mid = data().deepCopy(fields()[1].schema(), other.mid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.term)) {
        this.term = data().deepCopy(fields()[2].schema(), other.term);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.data)) {
        this.data = data().deepCopy(fields()[4].schema(), other.data);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Message instance
     * @param other The existing instance to copy.
     */
    private Builder(cn.atomicer.zephyr.raft.model.Message other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mid)) {
        this.mid = data().deepCopy(fields()[1].schema(), other.mid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.term)) {
        this.term = data().deepCopy(fields()[2].schema(), other.term);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.data)) {
        this.data = data().deepCopy(fields()[4].schema(), other.data);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestId() {
      return requestId;
    }

    /**
      * Sets the value of the 'requestId' field.
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mid' field.
      * @return The value.
      */
    public java.lang.CharSequence getMid() {
      return mid;
    }

    /**
      * Sets the value of the 'mid' field.
      * @param value The value of 'mid'.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder setMid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.mid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mid' field has been set.
      * @return True if the 'mid' field has been set, false otherwise.
      */
    public boolean hasMid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mid' field.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder clearMid() {
      mid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'term' field.
      * @return The value.
      */
    public java.lang.Integer getTerm() {
      return term;
    }

    /**
      * Sets the value of the 'term' field.
      * @param value The value of 'term'.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder setTerm(java.lang.Integer value) {
      validate(fields()[2], value);
      this.term = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'term' field has been set.
      * @return True if the 'term' field has been set, false otherwise.
      */
    public boolean hasTerm() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'term' field.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder clearTerm() {
      term = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder setType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[4], value);
      this.data = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public cn.atomicer.zephyr.raft.model.Message.Builder clearData() {
      data = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Message build() {
      try {
        Message record = new Message();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.mid = fieldSetFlags()[1] ? this.mid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.term = fieldSetFlags()[2] ? this.term : (java.lang.Integer) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.data = fieldSetFlags()[4] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Message>
    WRITER$ = (org.apache.avro.io.DatumWriter<Message>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Message>
    READER$ = (org.apache.avro.io.DatumReader<Message>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
