// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package cn.atomicer.raft.proto;

public interface EntryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EntryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 logIndex = 1;</code>
   */
  long getLogIndex();

  /**
   * <code>optional int64 createTerm = 2;</code>
   */
  long getCreateTerm();

  /**
   * <code>optional bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
