// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package cn.atomicer.raft.proto;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Vote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Vote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AppendEntriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AppendEntriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EntryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EntryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\005proto\"M\n\004Vote\022\016\n\006nodeI" +
      "d\030\001 \001(\t\022\014\n\004term\030\002 \001(\003\022\'\n\rlastEntryInfo\030\003" +
      " \001(\0132\020.proto.EntryInfo\"\232\001\n\024AppendEntries" +
      "Request\022\020\n\010leaderId\030\001 \001(\t\022\014\n\004term\030\002 \001(\003\022" +
      "\024\n\014prevLogIndex\030\003 \001(\003\022\023\n\013prevLogTerm\030\004 \001" +
      "(\003\022\024\n\014leaderCommit\030\005 \001(\003\022!\n\007entries\030\006 \003(" +
      "\0132\020.proto.EntryInfo\"?\n\tEntryInfo\022\020\n\010logI" +
      "ndex\030\001 \001(\003\022\022\n\ncreateTerm\030\002 \001(\003\022\014\n\004data\030\003" +
      " \001(\014\"\202\001\n\007Request\022 \n\004type\030\001 \001(\0162\022.proto.M" +
      "essageType\022\016\n\006nodeId\030\002 \001(\t\022\014\n\004term\030\003 \001(\003",
      "\022)\n\017lastEntriesInfo\030\004 \001(\0132\020.proto.EntryI" +
      "nfo\022\014\n\004data\030\005 \001(\014\"H\n\010Response\022 \n\004type\030\001 " +
      "\001(\0162\022.proto.MessageType\022\014\n\004term\030\002 \001(\003\022\014\n" +
      "\004data\030\003 \001(\014**\n\013MessageType\022\010\n\004DENY\020\000\022\006\n\002" +
      "OK\020\001\022\t\n\005ERROR\020\002B\032\n\026cn.atomicer.raft.prot" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Vote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Vote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Vote_descriptor,
        new java.lang.String[] { "NodeId", "Term", "LastEntryInfo", });
    internal_static_proto_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "LeaderId", "Term", "PrevLogIndex", "PrevLogTerm", "LeaderCommit", "Entries", });
    internal_static_proto_EntryInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_EntryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EntryInfo_descriptor,
        new java.lang.String[] { "LogIndex", "CreateTerm", "Data", });
    internal_static_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Request_descriptor,
        new java.lang.String[] { "Type", "NodeId", "Term", "LastEntriesInfo", "Data", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new java.lang.String[] { "Type", "Term", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
