// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package cn.atomicer.raft.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .proto.MessageType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .proto.MessageType type = 1;</code>
   */
  cn.atomicer.raft.proto.MessageType getType();

  /**
   * <code>optional string nodeId = 2;</code>
   */
  java.lang.String getNodeId();
  /**
   * <code>optional string nodeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>optional int64 term = 3;</code>
   */
  long getTerm();

  /**
   * <code>optional .proto.EntryInfo lastEntriesInfo = 4;</code>
   */
  boolean hasLastEntriesInfo();
  /**
   * <code>optional .proto.EntryInfo lastEntriesInfo = 4;</code>
   */
  cn.atomicer.raft.proto.EntryInfo getLastEntriesInfo();
  /**
   * <code>optional .proto.EntryInfo lastEntriesInfo = 4;</code>
   */
  cn.atomicer.raft.proto.EntryInfoOrBuilder getLastEntriesInfoOrBuilder();

  /**
   * <code>optional bytes data = 5;</code>
   */
  com.google.protobuf.ByteString getData();
}
