// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package cn.atomicer.raft.proto;

public interface VoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Vote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string nodeId = 1;</code>
   */
  java.lang.String getNodeId();
  /**
   * <code>optional string nodeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>optional int64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>optional .proto.EntryInfo lastEntryInfo = 3;</code>
   */
  boolean hasLastEntryInfo();
  /**
   * <code>optional .proto.EntryInfo lastEntryInfo = 3;</code>
   */
  cn.atomicer.raft.proto.EntryInfo getLastEntryInfo();
  /**
   * <code>optional .proto.EntryInfo lastEntryInfo = 3;</code>
   */
  cn.atomicer.raft.proto.EntryInfoOrBuilder getLastEntryInfoOrBuilder();
}
